version: "3.9"
services:
  webserver:
    image: "caddy"
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - "$PWD/html:/var/www/html"
      - "$PWD/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - cgi
      - db
  cgi:
    build:
      context: "backend"
      dockerfile: "phpWithPgsql.Dockerfile"
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: "Website_db
      POSTGRES_USER: "bjarni heselmans"
      POSTGRES_PASSWORD: "BjArNi"
    volumes:
      - db_data:/var/lib/postgresql/data
      
  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - db

volumes:
  db_data:
