version: '3.9'
services:
  webserver:
    image: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/html:/var/www/html"
      - "$PWD/Caddyfile:/etc/caddy/Caddyfile"
      - "$PWD/postgres_volume:/var/lib/postgresql/data"
    depends_on:
      - cgi
      - db
  cgi:
    build:
      context: "backend"
      dockerfile: "phpWithPgsql.Dockerfile"
    volumes:
      - "$PWD/html:/var/www/html"
      - "$PWD/postgres_volume:/var/lib/postgresql/data"
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: "website_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "gfg"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - db

volumes:
  postgres_volume:
