<!-- website.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title> Webtechnology project Home</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="styles.css"> <!-- separate CSS file -->
</head>
<body>

  <!-- Navbar -->
<nav class="w3-top">
  <div class="w3-bar w3-green w3-card w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-w>    <a href="index.php" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>
    <a href="About.html" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">>    <a href="Vieuw_data.html" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-wh>  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="index.php" class="w3-bar-item w3-button w3-padding-large">Home</a>
    <a href="About.html" class="w3-bar-item w3-button w3-padding-large">About</a>
    <a href="Vieuw_data.html" class="w3-bar-item w3-button w3-padding-large">Vieuw Data</a>
  </div>
</nav>

  <!-- Header -->
  <header class="w3-container w3-green w3-center" style="padding:128px 16px">
    <h1 class="w3-margin w3-jumbo">Webtechnology</h1>
    <p class="w3-xlarge">Bjarni Heselmans</p>
    <a href="Vieuw_data.html" class="w3-button w3-black w3-padding-large w3-large w3-margin-top">Vieu>  </header>

  <!-- Main Content -->
  <main class="w3-container">
    <!-- First Grid -->
    <section class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1>The Project:</h1>
          <p class="w3-text-grey">For my project, I created a website to display a random value from >                                  This site will provide continuous monitoring and visualization
          </p>
        </div>
      </div>
    </section>

    <section class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1>Working:</h1>
          <p class="w3-text-grey">I created a html file with a basic setup for documentation en enter>                                  Besides that I created a Vieuw Data page, this page is used for vis>                                  This can be done by everyone using the script I wrote: python.py.
                                  Furthermore i have a page about myself were i explain a litle bit m>          </p>
        </div>
        <div class="w3-third w3-center">
        </div>
      </div>
    </section>

    <section class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1>The Random Value:</h1>
          <p class="w3-text-grey">The random value is generated bye the script named: python.py in th>                                  The next step is to send this value to the data base I used the api>          </p>
        </div>
        <div class="w3-third w3-center">
        </div>
      </div>
    </section>

    <section class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1>Graph:</h1>
          <p class="w3-text-grey">In this graph I vissualize a value thats been collected by the data>                                 This will be plotted in a X-Y Graph.
          </p>
        </div>
        <div class="w3-third w3-center">
        </div>
      </div>
    </section>


  <!-- Footer -->
  <section class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <footer class="w3-container w3-padding-64 w3-center w3-opacity">
    <p>Website founded est 2024.</p>
  </section>
  </footer>

  <script>
    // Used to toggle the menu on small screens when clicking on the menu button
    function myFunction() {
      var x = document.getElementById("navDemo");
      if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
      } else {
        x.className = x.className.replace(" w3-show", "");
      }
    }
  </script>
</body>
</html>
