<!DOCTYPE html>
<html lang="en">
<head>
  <title>Webtechnology Project Home</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="styles.css"> <!-- Ensure this path is correct -->
</head>
<body>

  <!-- Navbar -->
  <nav class="w3-top">
    <div class="w3-bar w3-green w3-card w3-left-align w3-large">
      <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white" onclick="myFunction()"><i class="fa fa-bars"></i></a>
      <a href="index.php" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>
      <a href="About.html" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">About</a>
      <a href="Vieuw_data.html" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">View Data</a>
    </div>

    <!-- Navbar on small screens -->
    <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
      <a href="index.php" class="w3-bar-item w3-button w3-padding-large">Home</a>
      <a href="About.html" class="w3-bar-item w3-button w3-padding-large">About</a>
      <a href="Vieuw_data.html" class="w3-bar-item w3-button w3-padding-large">View Data</a>
    </div>
  </nav>

  <!-- Header -->
  <header class="w3-container w3-green w3-center" style="padding:128px 16px">
    <h1 class="w3-margin w3-jumbo">Webtechnology</h1>
    <p class="w3-xlarge">Bjarni Heselmans</p>
    <a href="Vieuw_data.html" class="w3-button w3-black w3-padding-large w3-large w3-margin-top">View Data</a>
  </header>

  <!-- Main Content -->
  <main class="w3-container">
    <!-- Dark Mode Toggle Switch -->
    <div class="dark-mode-container w3-center">
      <label for="dark-mode-switch" class="switch">
        <input type="checkbox" id="dark-mode-switch">
        <span class="slider round"></span>
      </label>
      <p>Dark Mode</p>
    </div>

    <!-- First Grid -->
    <section class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1>The Project:</h1>
          <p class="w3-text-grey">For my project, I created a website to display a random value from a script. This site will provide continuous monitoring and visualization.</p>
        </div>
      </div>
    </section>

    <section class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1>Working:</h1>
          <p class="w3-text-grey">I created an HTML file with a basic setup for documentation and interaction. Besides that, I created a View Data page, this page is used for visualizing data collected by the script I wrote: python.py.</p>
        </div>
      </div>
    </section>

    <section class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1>The Random Value:</h1>
          <p class="w3-text-grey">The random value is generated by the script named: python.py in the backend. This value is sent to the database via the API endpoint created.</p>
        </div>
      </div>
    </section>

    <section class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1>Graph:</h1>
          <p class="w3-text-grey">In this graph, I visualize a value that's been collected by the database. This will be plotted in an X-Y graph.</p>
        </div>
      </div>
    </section>
  </main>

  <!-- Footer -->
  <section class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <footer class="w3-container w3-padding-64 w3-center w3-opacity">
      <p>Website founded est 2024.</p>
    </footer>
  </section>

  <!-- JavaScript -->
  <script src="script.js"></script> <!-- Ensure this path is correct -->
  <script>
    // Used to toggle the menu on small screens when clicking on the menu button
    function myFunction() {
      var x = document.getElementById("navDemo");
      if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
      } else {
        x.className = x.className.replace(" w3-show", "");
      }
    }
  </script>
</body>
</html>
